<a href="https://colab.research.google.com/github/ShoebAgha/Pytorch/blob/main/Pytorch_Fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch

In [ ]:
torch.__version__

'2.8.0+cu126'

In [ ]:
scalar=torch.tensor(7)

In [ ]:
scalar.item()

7

In [ ]:
rand_tensor = torch.rand(size=(2,3,4))
rand_tensor,rand_tensor.shape, rand_tensor.ndim

(tensor([[[0.7625, 0.9168, 0.4660, 0.9681],
          [0.7907, 0.8132, 0.0294, 0.2817],
          [0.3221, 0.8483, 0.4028, 0.6879]],
 
         [[0.5549, 0.3142, 0.9369, 0.8881],
          [0.2922, 0.3755, 0.3413, 0.9501],
          [0.3784, 0.2673, 0.8553, 0.4903]]]),
 torch.Size([2, 3, 4]),
 3)

In [ ]:
zeros=torch.zeros(size=(1,7))
ones=torch.ones(size=(1,7))
zeros


tensor([[0., 0., 0., 0., 0., 0., 0.]])

In [ ]:
ones.dtype

torch.float32

In [ ]:
tensor_1=torch.rand(size=(3,2))
tensor_2=torch.rand(size=(2,3))

In [ ]:
torch.mm(tensor_1,tensor_2)

tensor([[0.3858, 0.7340, 0.6548],
        [0.0837, 0.1234, 0.1031],
        [0.7873, 1.3441, 1.1693]])

In [ ]:
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]], dtype=torch.float32)

tensor_B = torch.tensor([[7, 10],
                         [8, 11],
                         [9, 12]], dtype=torch.float32)


In [ ]:
x=torch.arange(0,100,10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [ ]:
torch.mean(x.type(torch.float32))

tensor(45.)

In [ ]:
x.min(), torch.sum(x)

(tensor(0), tensor(450))

In [ ]:
tensor=torch.arange(0,100,10)
print(f"Tensor: {tensor}")

print(f"Position of Min value: {tensor.argmin()}")
print(f"Position of Max value: {tensor.argmax()}")

Tensor: tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])
Position of Min value: 0
Position of Max value: 9


In [ ]:
x=torch.rand(size=(2,3))
x.reshape(shape=(3,2))

tensor([[0.9802, 0.9794],
        [0.8867, 0.7554],
        [0.9575, 0.2276]])

In [ ]:
x=x.reshape(1,6)
x

tensor([[0.9802, 0.9794, 0.8867, 0.7554, 0.9575, 0.2276]])

In [ ]:
torch.stack([x,x,x,x,x],dim=0).squeeze().squeeze()

tensor([[0.9802, 0.9794, 0.8867, 0.7554, 0.9575, 0.2276],
        [0.9802, 0.9794, 0.8867, 0.7554, 0.9575, 0.2276],
        [0.9802, 0.9794, 0.8867, 0.7554, 0.9575, 0.2276],
        [0.9802, 0.9794, 0.8867, 0.7554, 0.9575, 0.2276],
        [0.9802, 0.9794, 0.8867, 0.7554, 0.9575, 0.2276]])

In [58]:
torch.rand(size=(2,1,3,1)).squeeze()

tensor([[0.7521, 0.5939, 0.4916],
        [0.7234, 0.2847, 0.8918]])

In [61]:
torch.rand(size=(1,2,3)).permute(0,2,1).size()

torch.Size([1, 3, 2])

In [62]:
torch.cuda.is_available()

False

In [63]:
tensor.device

device(type='cpu')